// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// UrlContoller is an autogenerated mock type for the UrlContoller type
type UrlContoller struct {
	mock.Mock
}

// DeleteURL provides a mock function with given fields: ctx
func (_m *UrlContoller) DeleteURL(ctx *gin.Context) {
	_m.Called(ctx)
}

// GetURL provides a mock function with given fields: ctx
func (_m *UrlContoller) GetURL(ctx *gin.Context) {
	_m.Called(ctx)
}

// SaveURL provides a mock function with given fields: ctx
func (_m *UrlContoller) SaveURL(ctx *gin.Context) {
	_m.Called(ctx)
}

// NewUrlContoller creates a new instance of UrlContoller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUrlContoller(t interface {
	mock.TestingT
	Cleanup(func())
}) *UrlContoller {
	mock := &UrlContoller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
