env: "local"
storage_path: "./storage/storage.db"
http_server:
  addres: "localhost:8080"
  timeout: 4s
  idle_timeout: 60s
postgres_storage:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: 1423
  dbname: "postgres"